version: '1'

parser_type: html.parser

dag_config:
  description: Scrape latest feeds
  schedule: 0-59/5 * * * *
  start_date:
    year: 2023
    month: 04
    day: 13
  catchup: False
  is_paused_upon_creation: False

proxy:
  url: https://free-proxy-list.net/
  testing_url: https://google.com
  number_of_workers: 50
  number_checks: 3
  number_of_proxies: 50
  healthcheck: 0.66
  timeout: 10
  limit: 5
  storage:
    storage_key: proxy
    host: redis
    port: 6379
    db: 0


services:
  cnn-crawler:
    type: CNNCrawler
    args:
      url: "https://edition.cnn.com/"

  voa-crawler:
    type: VOACrawler
    args:
      url: "https://edition.cnn.com/"

